### ISSUE TITLE
ToDo: remove the multigroup icon from PlayerFrame

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicTBC#18]
![image](https://user-images.githubusercontent.com/1942409/124675931-ebbab880-debd-11eb-8e9e-b3ca29bb72be.png)

**Comment by XyzKangUI** [comment]
Try: 
local mg = PlayerPlayTime:GetParent().MultiGroupFrame
hooksecurefunc(mg, "Show", mg.Hide)

**Comment by Evolvee** [comment]
will try, thx

**Comment by Evolvee** [comment]
Seems to work, thanks!
