### ISSUE TITLE
Addon NiceDamage shows boxes instead of "+" signs and certain other number signs

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI-ClassicTBC#4]
Currently it displays fucked up characters, that does NOT happen on 2.4.3:

![image](https://user-images.githubusercontent.com/1942409/123920692-8418e080-d986-11eb-985f-4a988731965c.png)

**Comment by Evolvee** [comment]
fixed it for +healing

![image](https://user-images.githubusercontent.com/1942409/124673170-aba50700-deb8-11eb-8b84-26b3572c9c56.png)


now it seems to be only persistent for this 1 particular HK text

**Comment by XyzKangUI** [comment]
> fixed it for +healing
> 
> ![image](https://user-images.githubusercontent.com/1942409/124673170-aba50700-deb8-11eb-8b84-26b3572c9c56.png)
> 
> now it seems to be only persistent for this 1 particular HK text

The font misses "-" symbol.

**Comment by Evolvee** [comment]
yep

**Comment by XyzKangUI** [comment]
> yep
[pepsi.zip](https://github.com/Evolvee/EvolvePWPUI-ClassicTBC/files/7775993/pepsi.zip)

A more complete version of the font.

**Comment by Evolvee** [comment]
thx, will try
